No_permission: "&cNo permission"

Enderchest:
  1:
    displayname: "&6&lEnderchest &7| &8Level I"
    perm: "enderchest.level.1"
  2:
    displayname: "&6&lEnderchest &7| &8Level II"
    perm: "enderchest.level.2"
  3:
    displayname: "&6&lEnderchest &7| &8Level III"
    perm: "enderchest.level.3"
  4:
    displayname: "&6&lEnderchest &7| &8Level IV"
    perm: "enderchest.level.4"
  5:
    displayname: "&6&lEnderchest &7| &8Level V"
    perm: "enderchest.level.5"
  6:
    displayname: "&6&lEnderchest &7| &8Level VI"
    perm: "enderchest.level.6"