name: tEnderchest
main: net.helydev.com.EnderChest
description: This add-on is a custom ender chest system
version: 1.0-SNAPSHOT
author: ByJoako
commands:
  enderchest:
    aliases:
      - ec
      - pv